### PR TITLE
BVT Enhancements

### PR DESCRIPTION
**Pull request by crogers1**
autolaunch.py:
  * New script to handle automated testing. Runs test suites, which are just related bvt.py
	invocations. Has logic to enforce concurrency between test nodes, retrieve builds from
	build server, record logs, results, update mongo.

build_watcher.py:
  * New daemon to pull buildbot servers.  With ENABLE_BW_TEST flag set, will queue a test
	job after detecting a new build.  Updates mongo with new build/job information. Polling
	interval can be adjusted.

bvt.py:
  * Reworked version of 'experiments.py'.  bvt.py is a cleaner implementation. It is
	designed to run a single testcase with the provided flags.  Supports new testcase
	invocation method of dynamic module loading and introspection.  Added some additional
	cmd line options.

bvt_daemon.py:
  * New daemon to poll mongodb jobs collection and launch any queued jobs it finds,
	provided there exist available test nodes.  Keeps track of job status to determine
	success or failure.  Requeues jobs on failure to acquire a testing node.

controller.sh:
  * Start/stop/restart bvt_daemon and build_watcher simultaneously. Simplifies daemon management.

docs/*:
  * More detailed documentation on BVT architecture, setup, configuration, usage, and API.
	Documentation is always an ongoing process, so this needs to continue to be expanded.

execdaemon/execdaemon.py:
  * string should not be split before sending command to be executed on windows python.

infrastructure/*:
  * Needed to be imported from openxt-extras. As of now, this stuff is a requirement; it
	should ship with BVT until it can be decoupled.  At that time, it can be removed.

misc/*:
  * Directory for scripts no longer being used but still potentially useful. Would
	rather keep them than delete them until they are reintegrated/reimplemented/removed.

serverlib/show_table.py:
  * Create a new table to support display of test suite results.  Shows success/failure
	for each step in the test suite and overall test result.

serverlib/tags.py:
  * Support extra functionality for show_table with additional imports.

setup/00-install-prereqs.sh:
  * Use apt package management and pip to install all required packages for BVT. This includes
	python-daemon and Mongodb.

setup/01-install-tftp-pxe.sh:
  * Optional installation script to download/configure tftpd-hpa and setup a pxe server.
    Required for automated openxt installs.

setup/02-install-apache.sh:
  * Optional step to install apache web server. Useful for providing services to test machines
	if running with a subnet.

setup/03-install-dhcp-serv.sh:
  * Optional install and setup of isc-dhcp-server.  Not needed if user already has control
	of a dhcp server.  Otherwise, highly recommended for the majority of test cases.

setup/04-install-mms.sh:
  * Optional install of Mongo Management Studio. User friendly, open source gui front end
	for mongodb management.

setup/05-install-mail.sh:
  * Optional install of mailutils and postfix. Enables functionality in
	src/bvtlib/email_results.py, but is not required.

setup/06-setup-nodes.sh:
  * Optional configuration of 0 length files in bvt/nodes for autolaunch.py support. Needed
	for concurrency guaranteed by filelocks.

setup/dhcp.conf.template:
  * dhcp.conf template used for step 03-install-dhcp-serv.

setup/functions:
  * Common functions to be sourced by install scripts.

setup/install-deps.sh:
  * Run all install steps with this script.  Optional steps can be skipped with any modification.

bvtlib -> src/bvtlib and src/testcases:
  * Reorganized bvtlib/* into library modules and testcase modules. Ideal for testcase invocation
	through dynamic module loading.  Increased clarity and much more scalable than grouping
	everything in one subdirectory.  Most changes involved modifing import paths.

src/bvtlib/database_cursor.py:
  * not actively used, default to None for now. database credentials shouldn't be hardcoded
	anyway.

src/bvtlib/determine_build.py:
  * Query mongodb for current build on specified device under test.

src/bvtlib/dhcp.py:
  * Add extra check to verify dhcpd.conf exists in the directory.
  * Query mongodb for mac address of nic with AMT support on dut.

src/bvtlib/email_results.py:
  * Add support to email results of test suites to interested admins. Fairly basic
	information currently, room for expansion.

src/bvtlib/get_build.py:
  * /etc/issue build can be more than just numbers.
  * Try all-feed.conf method of getting build. If not default to
	whatever mongo has recorded for this test machine.

src/bvtlib/guest_ops.py:
  * Module containing operations to perform on guest VMs. Meant to be included
	as a library when writing new testcases.

src/bvtlib/have_driver.py:
  * Download devcon from upstream microsoft, unpack it, and then run it.

src/bvtlib/install_dotnet.py:
  * Update to new dotnet install convention, included on xctools.iso

src/bvtlib/install_tools_windows.py:
  * Reworked logic for installing xctools on windows. Performs reboots as each new server
	appears. In testing, this has been shown to be 1 service per reboot.
  * Support installing dev certs so 64 bit windows can install developer signed xctools

src/bvtlib/power_control.py:
  * Default power control to AMT. Pxe installing openxt is still supported even if AMT is not,
	so this is a fair assumption to make.
  * Rework logic for better stability.
  * Assumes amt-enabled nic aliased in etc/hosts with -amt suffix. Not thrilled about this
	but will be the standard for now.

src/bvtlib/reboot_windows_vm.py:
  * Actually include a function that attempts to reboot windows from inside the guest.

src/bvtlib/record_test.py:
  * Modify record_test to support test suites and their step structure.
  * Also support logging of job-ids so automated tests can be tracked.

src/bvtlib/run.py:
  * Support option to log to a file for additional debugging.
  * Shell should not always default to False on this case.

src/bvtlib/set_build_information.py:
  * Quietly update build info.
  * change _id to id, updated mongo convention.

src/bvtlib/set_pxe_build.py:
  * Add support to pass through secondary nic to ndvm so primary, amt enabled nic
	is still available while OpenXT is running.

src/bvtlib/settings.py:
  * Cleaned out many unused globals.  Also removed globals that shouldn't be globals.
  * Added globals to support new features. Should be overridden with private_settings.py
	if they're to be changed.

src/bvtlib/start_vm.py:
  * 600 sec timeout too long for start. Reduce to 300 seconds.

src/bvtlib/store_artifact.py:
  * pull from the test machine instead of pushing to the test controller.

src/bvtlib/wait_for_windows.py:
  * Race condition if wait_for_guest_to_start saw 'creating' as the state and
	unblocked before VM was running. Should wait till state == running.

src/bvtlib/wait_to_come_up.py:
  * If using two NIC setup to utilize AMT, installer should use hostname
	aliased to the IP allocated to AMT-enabled nic during install time checks.

src/testcases/accelerate_graphics.py:
  * Updated testcase to pull from microsoft. Find bdf of first non-integrated gpu.
	Not complete yet; last step requires automatically installing gfx drivers on guest.

src/testcases/dbus_logger.py:
  * Python connection library unneeded for this testcase, just use bvt run.

src/testcases/elevate_permissions.py:
  * Use pexpect and pxssh to verify that OpenXT install can be put into permissive mode.
    enter newrole, setenforce 0, remount rw.

src/testcases/enforce_encrypted_disks.py:
  * Remove logic to write to disk to verify strings don't show in encrypted disk.
	Should be in its own testcase. Use testcase to verify VM doesn't start after replacing
	encrypted disk.
  * Use the new guest_ops library to perform guest operations.

src/testcases/install_guest.py:
  * Check to see if host has wireless nic before adding to guest.
  * Don't install dotnet until we need it.
  * Don't check for 'freshness' of vhd.
  * Don't figure out base name, pass it explicitly.

src/testcases/install_python.py:
  * Minor fixes to install python on host.

src/testcases/install_tools.py:
  * More error catching for this testcase more robust for debugging.

src/testcases/pxe_install_xc.py:
  * Remove second set_pxe_build, unnecessary.
  * Don't need to update mongo here.
  * Use default_power_control to determine whether to refer to
	amt-enabled nic during install.
  * Lower timeout to reasonable value so install doesn't hang on failure.

src/testcases/reboot_test.py:
  * archive original reboot rest as 'old_reboot_test'
  * Add updated version using wait_to_come_up as verification
	host has booted properly.

src/testcases/soak.py:
  * In soak_up, don't default to pxe_boot, just turn the machine on.
	Fair assumption to make that the OpenXT has already been installed
	before we run this test.

src/testcase/store_status_report.py:
  * Implement a simplified version of store_status_report

src/testcases/upgrade_latest_release.py:
  * Support passing mac address so we can pxe upgrade.

webapp/results.py:
  * Support test suite results.

webapp/run_results.py:
  * Add support to display data about a test suite run.  Includes steps, pass/fail
	start/stop time.

webapp/scheduler.py:
  * Remove broken csrf. Can be added at a later time.
  * Add support to queue test jobs and display status information about them.

OXT-312

Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

### CODE REVIEW

**Comment by transpute** [comment]
This is a large set of changes.  Could you provide an overview in a JIRA ticket or on the mailing list?

**Comment by crogers1** [comment]
Of course.  I might not be able to make a writeup/ticket until tomorrow though.

**Comment by rossphilipson** [comment]
This one has been open for some time now and I don't think anyone is going to be able to fully review this. I know it is a giant change but to my understanding it is really a major re-factoring to move the BVT framework forward. Of course there may be regressions but at the moment BVT is basically in stasis with no one using it. I am inclined to merge this PR and let further BVT fixes and enhancement proceed. I will not do that for a couple of days though to let any discussion about this play out.

**Comment by transpute** [comment]
Would it be possible to separate the test cases PR from the test harness PR, or were all existing test cases invalidated by the test harness changes?

**Comment by crogers1** [comment]
I can't separate them; the new harness required removal of the test cases dictionary and the addition of entry functions to each test case.

**Comment by transpute** [comment]
If this PR is too big to fail, there is no choice but to merge without review.  The legacy-ioemu branch will provide a labelled checkpoint.

**Comment by rossphilipson** [comment]
@transpute is that a +1 on your part?

**Pull request merged**
